[profile.default]
contracts      = 'contracts'
test           = 'tests'
out            = 'out'
libs           = ['modules']
solc_version   = '0.8.19'
optimizer      = false
optimizer_runs = 200
verbosity      = 3

[fmt]
bracket_spacing = true
contract_new_lines = true
line_length = 140

[fuzz]
runs = 100

[invariant]
runs           = 10     # The number of calls to make in the invariant tests
depth          = 100    # The number of times to run the invariant tests
call_override  = false  # Override calls
fail_on_revert = true   # Fail the test if the contract reverts
